// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02sChxjF_ka5T7y6q_-Qp7qgYM2rKyhQ',
    appId: '1:229339792687:web:bd0a310b339f64d4440dda',
    messagingSenderId: '229339792687',
    projectId: 'loklok-app',
    authDomain: 'loklok-app.firebaseapp.com',
    storageBucket: 'loklok-app.appspot.com',
    measurementId: 'G-HC2SQWDZWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_M9t0fAhDZawQhKYk6tipIqAM8iHfMM',
    appId: '1:229339792687:android:9af236b323901483440dda',
    messagingSenderId: '229339792687',
    projectId: 'loklok-app',
    storageBucket: 'loklok-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD-C_1omqX6VToyfziR49tNC4GU4sM3mI',
    appId: '1:229339792687:ios:053e34c880bf6792440dda',
    messagingSenderId: '229339792687',
    projectId: 'loklok-app',
    storageBucket: 'loklok-app.appspot.com',
    iosBundleId: 'com.example.loklokapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD-C_1omqX6VToyfziR49tNC4GU4sM3mI',
    appId: '1:229339792687:ios:053e34c880bf6792440dda',
    messagingSenderId: '229339792687',
    projectId: 'loklok-app',
    storageBucket: 'loklok-app.appspot.com',
    iosBundleId: 'com.example.loklokapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02sChxjF_ka5T7y6q_-Qp7qgYM2rKyhQ',
    appId: '1:229339792687:web:120b5f334c687d3f440dda',
    messagingSenderId: '229339792687',
    projectId: 'loklok-app',
    authDomain: 'loklok-app.firebaseapp.com',
    storageBucket: 'loklok-app.appspot.com',
    measurementId: 'G-PLGBZFKPT1',
  );
}
